# ShortLink Redis 配置
bind 0.0.0.0
protected-mode no
port 6379
daemonize no
loglevel notice
logfile ""
databases 16

# 持久化
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# 内存
maxmemory-policy allkeys-lru
maxmemory 256mb

# 慢查询
slowlog-log-slower-than 10000
slowlog-max-len 128
