"""init: shortlinks + click_logs + users + blacklists

Revision ID: a9f2fc5aea29
Revises: 
Create Date: 2026-09-10 23:23:40.868571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f2fc5aea29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklists',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('click_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('short_code', sa.String(length=16), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referer', sa.String(length=512), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('click_logs', schema=None) as batch_op:
        batch_op.create_index('idx_click_logs_code_ip', ['short_code', 'ip'], unique=False)
        batch_op.create_index('idx_click_logs_code_time', ['short_code', 'clicked_at'], unique=False)

    op.create_table('short_links',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('short_code', sa.String(length=16), nullable=False),
    sa.Column('long_url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('click_limit', sa.Integer(), nullable=True),
    sa.Column('last_visit_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code'),
    sa.UniqueConstraint('url_hash')
    )
    with op.batch_alter_table('short_links', schema=None) as batch_op:
        batch_op.create_index('idx_short_links_expire', ['expire_at'], unique=False)
        batch_op.create_index('idx_short_links_status_deleted', ['status', 'is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_short_links_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('short_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_short_links_user_id'))
        batch_op.drop_index('idx_short_links_status_deleted')
        batch_op.drop_index('idx_short_links_expire')

    op.drop_table('short_links')
    with op.batch_alter_table('click_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_click_logs_code_time')
        batch_op.drop_index('idx_click_logs_code_ip')

    op.drop_table('click_logs')
    op.drop_table('blacklists')
    # ### end Alembic commands ###
